# Generated by Django 2.2.7 on 2020-01-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200125_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='isApproved',
            field=models.IntegerField(),
        ),
    ]
